import { TestAnswers } from '@src/models/test.model';

// Neutral score (+15)
export const neutralAnswers: TestAnswers = {
  galerie: { value: 5 },
  passions: {
    musics: 1,
    music01: null,
    music02: null,
    music03: null,
    music04: null,
    music05: null,
    music06: null,
    games: 1,
    game01: null,
    game02: null,
    game03: null,
    game04: null,
    game05: null,
    game06: null,
    game07: null,
    game08: null,
    game09: null,
    movies: 1,
    movie01: null,
    movie02: null,
    movie03: null,
    movie04: null,
    movie05: null,
    movie06: null,
    others: 1,
  },
  projets: {
    isDev: false,
    isRP: false,
    wantRP: false,
    isArt: false,
  },
  personnalite: {
    astro: null,
    quality01: null,
    quality02: null,
    quality03: null,
    quality04: null,
    quality05: null,
    quality06: null,
    quality07: null,
    quality08: null,
    flaw01: null,
    flaw02: null,
    flaw03: null,
    flaw04: null,
    flaw05: null,
    flaw06: null,
    flaw07: null,
    flaw08: null,
  },
  couple: {
    first: null,
    second: null,
    relations: null,
  },
  recherche: {
    bonus01: null,
    bonus02: null,
    bonus03: null,
    bonus04: null,
    bonus05: null,
    bonus06: null,
    malus01: null,
    malus02: null,
    malus03: null,
    malus04: null,
    malus05: null,
    malus06: null,
    canFree: false,
    hasFree: false,
    distance: false,
    physical: 5,
  },
  sexe: {
    role: null,
    penetration: null,
    orgasm: null,
    physical: 5,
    sexe: 5,
  },
};

// Min score (-70)
export const minAnswers: TestAnswers = {
  galerie: { value: 0 },
  passions: {
    musics: 0,
    music01: false,
    music02: false,
    music03: false,
    music04: false,
    music05: false,
    music06: false,
    games: 0,
    game01: false,
    game02: false,
    game03: false,
    game04: false,
    game05: false,
    game06: false,
    game07: false,
    game08: false,
    game09: false,
    movies: 0,
    movie01: false,
    movie02: false,
    movie03: false,
    movie04: false,
    movie05: false,
    movie06: false,
    others: 0,
  },
  projets: {
    isDev: false,
    isRP: false,
    wantRP: false,
    isArt: false,
  },
  personnalite: {
    astro: false,
    quality01: false,
    quality02: false,
    quality03: false,
    quality04: false,
    quality05: false,
    quality06: false,
    quality07: false,
    quality08: false,
    flaw01: false,
    flaw02: false,
    flaw03: false,
    flaw04: false,
    flaw05: false,
    flaw06: false,
    flaw07: false,
    flaw08: false,
  },
  couple: {
    first: -1,
    second: -1,
    relations: -1,
  },
  recherche: {
    bonus01: false,
    bonus02: false,
    bonus03: false,
    bonus04: false,
    bonus05: false,
    bonus06: false,
    malus01: true,
    malus02: true,
    malus03: true,
    malus04: true,
    malus05: true,
    malus06: true,
    canFree: false,
    hasFree: false,
    distance: false,
    physical: 0,
  },
  sexe: {
    role: -1,
    penetration: -1,
    orgasm: -1,
    physical: 0,
    sexe: 0,
  },
};

// Max score (+122)
export const maxAnswers: TestAnswers = {
  galerie: { value: 10 },
  passions: {
    musics: 5,
    music01: true,
    music02: true,
    music03: true,
    music04: true,
    music05: true,
    music06: true,
    games: 5,
    game01: true,
    game02: true,
    game03: true,
    game04: true,
    game05: true,
    game06: true,
    game07: true,
    game08: true,
    game09: true,
    movies: 5,
    movie01: true,
    movie02: true,
    movie03: true,
    movie04: true,
    movie05: true,
    movie06: true,
    others: 5,
  },
  projets: {
    isDev: true,
    isRP: true,
    wantRP: true,
    isArt: true,
  },
  personnalite: {
    astro: true,
    quality01: true,
    quality02: true,
    quality03: true,
    quality04: true,
    quality05: true,
    quality06: true,
    quality07: true,
    quality08: true,
    flaw01: true,
    flaw02: true,
    flaw03: true,
    flaw04: true,
    flaw05: true,
    flaw06: true,
    flaw07: true,
    flaw08: true,
  },
  couple: {
    first: 5,
    second: 5,
    relations: 5,
  },
  recherche: {
    bonus01: true,
    bonus02: true,
    bonus03: true,
    bonus04: true,
    bonus05: true,
    bonus06: true,
    malus01: false,
    malus02: false,
    malus03: false,
    malus04: false,
    malus05: false,
    malus06: false,
    canFree: true,
    hasFree: true,
    distance: true,
    physical: 10,
  },
  sexe: {
    role: 3,
    penetration: 3,
    orgasm: 3,
    physical: 10,
    sexe: 10,
  },
};
